# minui-keyboard - On-screen keyboard utility
#
# Uses shared build patterns from common/build.mk

TARGET = minui-keyboard

# Utils are at workspace/all/utils/foo/ - 3 levels to workspace/
PLATFORM_DEPTH = ../../../

EXTRA_CFLAGS = -std=gnu99

include ../../common/build.mk
