# Input pak - button configuration tool
#
# Uses shared build patterns from common/build.mk

TARGET = minput

# Paks are one level deeper than utils (paks/Input/src/ vs utils/foo/)
PLATFORM_DEPTH = ../../../../

# Output goes to parent directory's build folder with .elf extension
BUILD_DIR = ../build
BINARY_EXT = .elf

include ../../../common/build.mk
