# Clock pak - displays current time
#
# Uses shared build patterns from common/build.mk

TARGET = clock

# Paks are one level deeper than utils (paks/Clock/src/ vs utils/foo/)
PLATFORM_DEPTH = ../../../../

# Output goes to parent directory's build folder with .elf extension
BUILD_DIR = ../build
BINARY_EXT = .elf

include ../../../common/build.mk
