$(PLATFORM):
	# $@
	cp ./workspace/$@/show/show.elf ./build/SYSTEM/$@/bin
	# installer
	cp ./workspace/$@/install/update.sh ./build/SYSTEM/$@/bin/install.sh
	mkdir -p ./build/BOOT/common/$@/
	cp ./workspace/$@/install/boot.sh ./build/BOOT/common/$@.sh
	cp ./workspace/$@/show/show.elf ./build/BOOT/common/$@/
	# boot assets
	cp ./skeleton/SYSTEM/res/installing@2x.png ./build/BOOT/common/$@/installing.png
	cp ./skeleton/SYSTEM/res/updating@2x.png ./build/BOOT/common/$@/updating.png
